// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZ5mOg4lGD5glJaXzuJppXQHx-hjunmHg',
    appId: '1:555417267679:web:e351324cf35f4e1612e86a',
    messagingSenderId: '555417267679',
    projectId: 'notesapp-c408f',
    authDomain: 'notesapp-c408f.firebaseapp.com',
    storageBucket: 'notesapp-c408f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6s2Y2p0Qbvg5pOOk2xuaploW8Ifq7-nM',
    appId: '1:555417267679:android:c54cce82721484df12e86a',
    messagingSenderId: '555417267679',
    projectId: 'notesapp-c408f',
    storageBucket: 'notesapp-c408f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzAatkeBOZhl1VWO8bFgWH28ZQppf1uNk',
    appId: '1:555417267679:ios:b8179cb6af631f3512e86a',
    messagingSenderId: '555417267679',
    projectId: 'notesapp-c408f',
    storageBucket: 'notesapp-c408f.appspot.com',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzAatkeBOZhl1VWO8bFgWH28ZQppf1uNk',
    appId: '1:555417267679:ios:b8179cb6af631f3512e86a',
    messagingSenderId: '555417267679',
    projectId: 'notesapp-c408f',
    storageBucket: 'notesapp-c408f.appspot.com',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZ5mOg4lGD5glJaXzuJppXQHx-hjunmHg',
    appId: '1:555417267679:web:f017e9eab6c38b0c12e86a',
    messagingSenderId: '555417267679',
    projectId: 'notesapp-c408f',
    authDomain: 'notesapp-c408f.firebaseapp.com',
    storageBucket: 'notesapp-c408f.appspot.com',
  );
}
